# Generated by Django 2.0.4 on 2018-12-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('logoImg', models.CharField(max_length=3000)),
                ('text', models.CharField(max_length=1000)),
                ('issuerID', models.CharField(max_length=500)),
                ('chain', models.CharField(max_length=500)),
                ('transactionID', models.CharField(max_length=200)),
                ('issuedOn', models.CharField(max_length=100)),
            ],
        ),
    ]
