# Generated by Django 2.0.4 on 2018-12-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certviewer', '0004_certificate_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='logoImg',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signatureImg',
            field=models.FileField(upload_to=''),
        ),
    ]
