# Generated by Django 2.0.4 on 2018-12-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certviewer', '0005_auto_20181214_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncertificate',
            name='json',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
