# Generated by Django 2.0.4 on 2018-12-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certviewer', '0006_auto_20181217_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsoncertificate',
            name='issuerID',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuerID',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='logoImg',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='signatureImg',
            field=models.CharField(max_length=8000),
        ),
    ]
